# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69a7cdfe4df143b08815354d745e3997cb540b9bf1e6dda7c44d1e2603aa4f1101dce26e66f84b43696ef989fafcf1f019287a660031283d92e2f78f50bc0e67

test:
  secret_key_base: 89ced5c87bd3f40658bdab14b4b64c2c8d1a50da1e1c6368c886e6e01dce643f642b6a7445902e525de34e4ba4e975a67d46023a92ccbfb5d4430a5f40f25b1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
